"""
Email utility for sending resume analysis results
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from typing import Dict, Optional
import os


def send_analysis_email(
    recipient_email: str,
    analysis_result: Dict,
    pdf_report: bytes,
    resume_filename: str,
    smtp_config: Optional[Dict] = None,
) -> Dict[str, any]:
    """
    Send resume analysis via email

    Args:
        recipient_email: Recipient's email address
        analysis_result: Analysis results dictionary
        pdf_report: PDF report as bytes
        resume_filename: Original resume filename
        smtp_config: SMTP configuration (server, port, email, password)

    Returns:
        Dictionary with send status
    """
    try:
        # Default SMTP config (Gmail)
        if not smtp_config:
            smtp_config = {
                "server": "smtp.gmail.com",
                "port": 587,
                "email": os.getenv("SMTP_EMAIL", ""),
                "password": os.getenv("SMTP_PASSWORD", ""),
            }

        if not smtp_config["email"] or not smtp_config["password"]:
            return {
                "success": False,
                "error": "SMTP credentials not configured. Please set SMTP_EMAIL and SMTP_PASSWORD in .env file",
            }

        # Create message
        msg = MIMEMultipart()
        msg["From"] = smtp_config["email"]
        msg["To"] = recipient_email
        msg["Subject"] = f"Resume Analysis Results - {resume_filename}"

        # Email body
        match_score = analysis_result.get("match_score", 0)
        match_rating = analysis_result.get("match_rating", "N/A")

        body = f"""
        <html>
        <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
            <h2 style="color: #0ea5e9;">Resume Analysis Results</h2>
            
            <div style="background: #f9fafb; padding: 20px; border-radius: 8px; margin: 20px 0;">
                <h3 style="margin-top: 0;">Resume: {resume_filename}</h3>
                <p><strong>Match Score:</strong> <span style="font-size: 24px; color: #0ea5e9;">{match_score}%</span></p>
                <p><strong>Rating:</strong> {match_rating}</p>
            </div>
            
            <h3>Match Reasoning:</h3>
            <p>{analysis_result.get("match_reasoning", "N/A")}</p>
            
            <h3>Key Findings:</h3>
            <ul>
                <li><strong>Technical Skills Found:</strong> {len(analysis_result.get("found_keywords", {}).get("technical_skills", []))}</li>
                <li><strong>Soft Skills Found:</strong> {len(analysis_result.get("found_keywords", {}).get("soft_skills", []))}</li>
                <li><strong>Critical Skills Missing:</strong> {len(analysis_result.get("missing_keywords", {}).get("critical_technical_skills", []))}</li>
            </ul>
            
            <h3>Top Suggestions:</h3>
            <ol>
        """

        # Add top 5 suggestions
        suggestions = analysis_result.get("suggestions", [])[:5]
        for suggestion in suggestions:
            body += f"<li>{suggestion}</li>\n"

        body += """
            </ol>
            
            <p style="margin-top: 30px;">
                <em>Please find the detailed analysis report attached as PDF.</em>
            </p>
            
            <hr style="margin: 30px 0; border: none; border-top: 1px solid #e5e7eb;">
            <p style="color: #6b7280; font-size: 12px;">
                This email was generated by Resume Keyword Matcher<br>
                For best results, review the attached PDF report for complete analysis.
            </p>
        </body>
        </html>
        """

        msg.attach(MIMEText(body, "html"))

        # Attach PDF report
        if pdf_report:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(pdf_report)
            encoders.encode_base64(part)
            part.add_header(
                "Content-Disposition",
                f"attachment; filename=resume_analysis_{resume_filename.replace('.pdf', '')}.pdf",
            )
            msg.attach(part)

        # Send email
        server = smtplib.SMTP(smtp_config["server"], smtp_config["port"])
        server.starttls()
        server.login(smtp_config["email"], smtp_config["password"])
        server.send_message(msg)
        server.quit()

        return {
            "success": True,
            "message": f"Analysis results sent successfully to {recipient_email}",
        }

    except smtplib.SMTPAuthenticationError:
        return {
            "success": False,
            "error": "SMTP Authentication failed. Check your email and password.",
        }
    except smtplib.SMTPException as e:
        return {"success": False, "error": f"SMTP Error: {str(e)}"}
    except Exception as e:
        return {"success": False, "error": f"Error sending email: {str(e)}"}


def validate_email(email: str) -> bool:
    """
    Validate email format

    Args:
        email: Email address to validate

    Returns:
        True if valid, False otherwise
    """
    import re

    pattern = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
    return bool(re.match(pattern, email))


def get_smtp_config_instructions() -> str:
    """
    Return instructions for SMTP configuration

    Returns:
        Markdown formatted instructions
    """
    return """
    ### 📧 Email Configuration Setup
    
    To enable email functionality, you need to configure SMTP settings:
    
    #### For Gmail:
    1. Enable 2-Factor Authentication on your Google account
    2. Generate an "App Password":
       - Go to Google Account Settings → Security
       - Select "2-Step Verification"
       - Scroll to "App passwords"
       - Generate a new app password for "Mail"
    3. Add to your `.env` file:
       ```
       SMTP_EMAIL=your.email@gmail.com
       SMTP_PASSWORD=your_app_password_here
       ```
    
    #### For Other Email Providers:
    - **Outlook/Hotmail**: 
      - Server: `smtp-mail.outlook.com`, Port: `587`
    - **Yahoo**: 
      - Server: `smtp.mail.yahoo.com`, Port: `587`
    
    Add these to your `.env` file along with your credentials.
    
    ⚠️ **Security Note**: Never share your app password or commit it to version control!
    """
