"""PDF report generation utility"""

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from datetime import datetime
import io
from typing import Dict, Any


def create_analysis_report(
    analysis_data: Dict[str, Any], resume_filename: str
) -> io.BytesIO:
    """
    Generate a PDF report of the resume analysis.

    Args:
        analysis_data: Dictionary containing analysis results
        resume_filename: Name of the analyzed resume file

    Returns:
        BytesIO buffer containing the PDF
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=18,
    )

    # Container for the 'Flowable' objects
    elements = []

    # Define styles
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=24,
        textColor=colors.HexColor("#6366F1"),
        spaceAfter=30,
        alignment=TA_CENTER,
        fontName="Helvetica-Bold",
    )

    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontSize=16,
        textColor=colors.HexColor("#6366F1"),
        spaceAfter=12,
        spaceBefore=12,
        fontName="Helvetica-Bold",
    )

    subheading_style = ParagraphStyle(
        "CustomSubHeading",
        parent=styles["Heading3"],
        fontSize=12,
        textColor=colors.HexColor("#8B5CF6"),
        spaceAfter=8,
        spaceBefore=8,
        fontName="Helvetica-Bold",
    )

    normal_style = ParagraphStyle(
        "CustomNormal",
        parent=styles["Normal"],
        fontSize=10,
        spaceAfter=6,
        alignment=TA_JUSTIFY,
    )

    # Title
    title = Paragraph("Resume Analysis Report", title_style)
    elements.append(title)

    # Metadata
    metadata = f"""
    <b>Resume:</b> {resume_filename}<br/>
    <b>Analysis Date:</b> {datetime.now().strftime("%B %d, %Y at %I:%M %p")}<br/>
    <b>Generated by:</b> Resume Keyword Matcher
    """
    elements.append(Paragraph(metadata, normal_style))
    elements.append(Spacer(1, 20))

    # Match Score Section
    match_score = analysis_data.get("match_score", 0)
    rating, _ = get_rating_for_score(match_score)

    score_heading = Paragraph("Overall Match Score", heading_style)
    elements.append(score_heading)

    score_text = f"""
    <b>Score:</b> {match_score}% - {rating}<br/>
    <b>Reasoning:</b> {analysis_data.get("match_reasoning", "No reasoning provided")}
    """
    elements.append(Paragraph(score_text, normal_style))
    elements.append(Spacer(1, 15))

    # Strengths Section
    if "strengths" in analysis_data and analysis_data["strengths"]:
        strengths_heading = Paragraph("Key Strengths", heading_style)
        elements.append(strengths_heading)

        for strength in analysis_data["strengths"]:
            bullet = Paragraph(f"• {strength}", normal_style)
            elements.append(bullet)

        elements.append(Spacer(1, 15))

    # Found Keywords Section
    found_keywords = analysis_data.get("found_keywords", {})
    if any(found_keywords.values()):
        found_heading = Paragraph("Keywords Found in Resume", heading_style)
        elements.append(found_heading)

        if found_keywords.get("technical_skills"):
            subhead = Paragraph("Technical Skills", subheading_style)
            elements.append(subhead)
            skills_text = ", ".join(found_keywords["technical_skills"])
            elements.append(Paragraph(skills_text, normal_style))

        if found_keywords.get("soft_skills"):
            subhead = Paragraph("Soft Skills", subheading_style)
            elements.append(subhead)
            skills_text = ", ".join(found_keywords["soft_skills"])
            elements.append(Paragraph(skills_text, normal_style))

        if found_keywords.get("experience_keywords"):
            subhead = Paragraph("Experience Keywords", subheading_style)
            elements.append(subhead)
            exp_text = ", ".join(found_keywords["experience_keywords"])
            elements.append(Paragraph(exp_text, normal_style))

        if found_keywords.get("education_keywords"):
            subhead = Paragraph("Education Keywords", subheading_style)
            elements.append(subhead)
            edu_text = ", ".join(found_keywords["education_keywords"])
            elements.append(Paragraph(edu_text, normal_style))

        elements.append(Spacer(1, 15))

    # Missing Keywords Section
    missing_keywords = analysis_data.get("missing_keywords", {})
    if any(missing_keywords.values()):
        missing_heading = Paragraph("Missing Keywords & Gaps", heading_style)
        elements.append(missing_heading)

        if missing_keywords.get("critical_technical_skills"):
            subhead = Paragraph("Critical Technical Skills", subheading_style)
            elements.append(subhead)
            for skill in missing_keywords["critical_technical_skills"]:
                bullet = Paragraph(f"• {skill}", normal_style)
                elements.append(bullet)

        if missing_keywords.get("important_soft_skills"):
            subhead = Paragraph("Important Soft Skills", subheading_style)
            elements.append(subhead)
            for skill in missing_keywords["important_soft_skills"]:
                bullet = Paragraph(f"• {skill}", normal_style)
                elements.append(bullet)

        if missing_keywords.get("experience_gaps"):
            subhead = Paragraph("Experience Gaps", subheading_style)
            elements.append(subhead)
            for gap in missing_keywords["experience_gaps"]:
                bullet = Paragraph(f"• {gap}", normal_style)
                elements.append(bullet)

        if missing_keywords.get("education_gaps"):
            subhead = Paragraph("Education Gaps", subheading_style)
            elements.append(subhead)
            for gap in missing_keywords["education_gaps"]:
                bullet = Paragraph(f"• {gap}", normal_style)
                elements.append(bullet)

        elements.append(Spacer(1, 15))

    # Suggestions Section
    if "suggestions" in analysis_data and analysis_data["suggestions"]:
        suggestions_heading = Paragraph(
            "Recommendations for Improvement", heading_style
        )
        elements.append(suggestions_heading)

        for i, suggestion in enumerate(analysis_data["suggestions"], 1):
            bullet = Paragraph(f"{i}. {suggestion}", normal_style)
            elements.append(bullet)

        elements.append(Spacer(1, 15))

    # ATS Optimization Tips
    if (
        "ats_optimization_tips" in analysis_data
        and analysis_data["ats_optimization_tips"]
    ):
        ats_heading = Paragraph("ATS Optimization Tips", heading_style)
        elements.append(ats_heading)

        for tip in analysis_data["ats_optimization_tips"]:
            bullet = Paragraph(f"• {tip}", normal_style)
            elements.append(bullet)

        elements.append(Spacer(1, 15))

    # Footer
    footer_text = """
    <i>This report was generated by Resume Keyword Matcher using AI analysis. 
    Use these insights as guidance to improve your resume for better ATS compatibility and recruiter appeal.</i>
    """
    elements.append(Spacer(1, 30))
    elements.append(Paragraph(footer_text, normal_style))

    # Build PDF
    doc.build(elements)

    # Get the value of the BytesIO buffer
    pdf = buffer.getvalue()
    buffer.close()

    # Return as new BytesIO for download
    return io.BytesIO(pdf)


def get_rating_for_score(score: float) -> tuple[str, str]:
    """
    Get rating text and color based on score.

    Args:
        score: Match score (0-100)

    Returns:
        Tuple of (rating_text, color_hex)
    """
    if score >= 71:
        return "Excellent Match", "#10B981"
    elif score >= 41:
        return "Good Match", "#F59E0B"
    else:
        return "Needs Improvement", "#EF4444"
